/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itdog_pushflow_NativeBridge */

#ifndef _Included_com_itdog_pushflow_NativeBridge
#define _Included_com_itdog_pushflow_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itdog_pushflow_NativeBridge
 * Method:    pushFlow
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_itdog_pushflow_NativeBridge_pushFlow
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
