/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itdog_android_ffmpeg_videoplayer_VideoPlayer */

#ifndef _Included_com_itdog_android_ffmpeg_videoplayer_VideoPlayer
#define _Included_com_itdog_android_ffmpeg_videoplayer_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itdog_android_ffmpeg_videoplayer_VideoPlayer
 * Method:    play
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_itdog_android_1ffmpeg_1videoplayer_VideoPlayer_play
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
