/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itdog_ffmpegdemo_NativeBridge */

#ifndef _Included_com_itdog_ffmpegdemo_NativeBridge
#define _Included_com_itdog_ffmpegdemo_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itdog_ffmpegdemo_NativeBridge
 * Method:    urlprotocolinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itdog_ffmpegdemo_NativeBridge_urlprotocolinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_itdog_ffmpegdemo_NativeBridge
 * Method:    avformatinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itdog_ffmpegdemo_NativeBridge_avformatinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_itdog_ffmpegdemo_NativeBridge
 * Method:    avcodecinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itdog_ffmpegdemo_NativeBridge_avcodecinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_itdog_ffmpegdemo_NativeBridge
 * Method:    avfilterinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itdog_ffmpegdemo_NativeBridge_avfilterinfo
  (JNIEnv *, jclass);

/*
 * Class:     com_itdog_ffmpegdemo_NativeBridge
 * Method:    configurationinfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_itdog_ffmpegdemo_NativeBridge_configurationinfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
