/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itdog_recordvideo_NativeBridge */

#ifndef _Included_com_itdog_recordvideo_NativeBridge
#define _Included_com_itdog_recordvideo_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itdog_recordvideo_NativeBridge
 * Method:    init
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_itdog_recordvideo_NativeBridge_init
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_itdog_recordvideo_NativeBridge
 * Method:    start
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_itdog_recordvideo_NativeBridge_start
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_itdog_recordvideo_NativeBridge
 * Method:    startAudio
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_itdog_recordvideo_NativeBridge_startAudio
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_itdog_recordvideo_NativeBridge
 * Method:    flush
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_itdog_recordvideo_NativeBridge_flush
  (JNIEnv *, jclass);

/*
 * Class:     com_itdog_recordvideo_NativeBridge
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_itdog_recordvideo_NativeBridge_close
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
