/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itdog_decoder_NativeBridge */

#ifndef _Included_com_itdog_decoder_NativeBridge
#define _Included_com_itdog_decoder_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itdog_decoder_NativeBridge
 * Method:    getVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_itdog_decoder_NativeBridge_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_itdog_decoder_NativeBridge
 * Method:    decode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_itdog_decoder_NativeBridge_decode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
